/// \file
/// \ingroup tutorial_tree
/// \notebook -nodraw
/// Example of Root macro to copy a subset of a Tree to a new Tree, selecting entries.
///
/// Only selected entries are copied to the new Tree.
/// The input file has been generated by the program in `$ROOTSYS/test/Event`
/// with `Event 1000 1 99 1`
///
/// \macro_code
///
/// \author Rene Brun


void ApplyCuts()
{
   // Get old file, old tree and set top branch address

   TString FileDir = "/home/ryan/anaconda3/envs/my_root_env/Project/Datasets/";
   TString Data2012FileName = "KstKst_RealData_2012.root";
   TString Data2018FileName = "KstKst_RealData_2018.root";

   TFile *Old2012File = new TFile(FileDir+Data2012FileName);
   TTree *Old2012Tree = (TTree*)Old2012File->Get("DecayTree");

   Int_t Data2012Entries = Old2012Tree->GetEntries();

   Float_t Comb_Bkg_BDTD_Score, PID_Combined_Var_BDTG_Score;
   Old2012Tree->SetBranchAddress("Comb_Bkg_BDTD_Score", &Comb_Bkg_BDTD_Score);
   Old2012Tree->SetBranchAddress("PID_Combined_Var_BDTG_Score", &PID_Combined_Var_BDTG_Score);

   // Create a new file + a clone of old tree in new file
   TFile New2012File("KstKst_RealData_2012_Cut.root", "recreate");
   auto New2012Tree = Old2012Tree->CloneTree(0);
   //TTree *New2012Tree = (TTree*)Old2012Tree->CloneTree(0);

   for (Long64_t ievt=0; ievt<Data2012Entries; ievt++) {
      Old2012Tree->GetEntry(ievt);
      if (Comb_Bkg_BDTD_Score > 0.0013 && PID_Combined_Var_BDTG_Score > 0.5)
         New2012Tree->Fill();
   }

   New2012Tree->Print();
   New2012File.Write();
}

int main(int argc, char const *argv[])
{
   ApplyCuts();
   return 0;
}